# Generated by Django 6.0.3 on 2026-04-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='transcript',
            field=models.TextField(blank=True),
        ),
    ]
