# Generated by Django 6.0.3 on 2026-05-06 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quiz_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='youtube_url',
            new_name='url',
        ),
    ]
